# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('eventoPrincipal', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=10)),
                ('dataEHoraDeInicio', models.DateTimeField(blank=True, null=True)),
                ('palavrasChave', models.CharField(max_length=150)),
                ('logotipo', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('endereço', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabalho.Pessoa')),
                ('curriculo', models.CharField(max_length=150)),
                ('artigos', models.ManyToManyField(blank=True, to='trabalho.ArtigoCientifico')),
            ],
            bases=('trabalho.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabalho.Evento')),
                ('issn', models.CharField(max_length=150)),
            ],
            bases=('trabalho.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabalho.Pessoa')),
                ('cpf', models.CharField(max_length=12)),
            ],
            bases=('trabalho.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabalho.Pessoa')),
                ('cnpj', models.CharField(max_length=50)),
                ('razaosocial', models.CharField(max_length=150)),
            ],
            bases=('trabalho.pessoa',),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trabalho.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trabalho.EventoCientifico'),
        ),
    ]
